### ISSUE TITLE
Do we want to continue to use GitHub as a tool for organization?

### ISSUE THREAD

**Issue by stpaultim** [stpaultim/twin-cities-meeting-space#17]
We started out using GitHub to track discussions and document our project, because it is a familiar default tool to use at Hack-A-Thons. It has it's advantages and disadvantages.

Disadvantages:

1) It's a geeky tool and not nearly as user friendly as other options out there. 
2) Specially - It does not seem to be very easy to see recent comments on "issues." I can see which issues have been updated, but I don't know if it was me that updated them or someone else?

Advantages:

1) It's does much of what we need, is free, and is a reliable default choice (choosing an alternative will be a big discussion - everyone has their own favorites). 
2) It provides built in access and visibility to the entire open source world. 
3) Using it - helps familiarize us with tools that lots of other open source folks use and that we may need to use in the future. 

NOTE: It's not an either/or situation. We can use GitHub for some tasks and move other tasks to other tools.

**Comment by Derkscholtz** [comment]
Not knowing other alternatives, I'm leaning towards staying with github.
The open source community aspect seems especially compelling.

D

**Comment by boskybay** [comment]
It's not a bad idea to continue using it. I'd need to put some time in
getting comfortable with the various jargon and what the fucntional
workflows are.
And similarly for me, this would be the only thing I'd be using GitHub for,
though perhaps it would open other opportunities. So I'm open to it but
there'd be a learning curve.
Kathy

Kathy Ahlers
(763) 789-7143
(763) 639-6498 cell | phone & text

**Comment by stpaultim** [comment]
We decided at our meeting to go ahead and use GitHub for now. We can change our mind as time goes on, if this does not work as a tool. 

I will close this issue.
