### ISSUE TITLE
Schedule our next meeting

### ISSUE THREAD

**Issue by stpaultim** [stpaultim/twin-cities-meeting-space#5]
We need to schedule a follow up meeting to decide on next steps.

**Comment by stpaultim** [comment]
It will be at least a week before I'm able to meet, but sometime after March 20th will work for me. In the meantime, I'll continue to play around with our prototype site adding and testing features. We can use the "Issues" in GitHub to prepare for the next meeting and to make some progress prior to a meeting.

**Comment by stpaultim** [comment]
I set up a doodle for our next meeting:

   http://doodle.com/poll/diri3azy8fdv9ptn

Tim

**Comment by boskybay** [comment]
Tim, On the Doodle, did you really mean 1 am on April 2? I can't meet then,
but wondered about that.

Kathy

Kathy Ahlers
(763) 789-7143
(763) 639-6498 cell | phone & text
